// adapter.js — Browser polyfills for WeChat Mini Game
// Generated by MiniGameBackend

console.log('[adapter] Starting adapter initialization');

// === Shared Module object (must be before any subpackage loads) ===
// Both freetype.js and app.js reference this shared object via globalThis.Module.
// Without this, parallel subpackage loading causes a race: app.js may load
// before freetype.js and capture an empty {} instead of the FreeType Module.
if (!globalThis.Module) globalThis.Module = {};

// === console polyfill (must be first — other polyfills use console.log) ===
if (typeof globalThis.console === 'undefined') {
    globalThis.console = { log: function(){}, error: function(){}, warn: function(){} };
}

// === window polyfill ===
// WeChat provides globalThis.window as a read-only getter on some platforms,
// but on real devices window may be completely undefined.
(function() {
    var win = (typeof window !== 'undefined') ? window : globalThis.window;
    if (!win) {
        win = globalThis;
        globalThis.window = globalThis;
        console.log('[adapter] window was undefined, created as globalThis alias');
    } else {
        console.log('[adapter] win exists, typeof win:', typeof win);
    }
    if (typeof win.requestAnimationFrame === 'undefined') {
        win.requestAnimationFrame = function(cb) { return setTimeout(cb, 16); };
    }
    if (typeof win.cancelAnimationFrame === 'undefined') {
        win.cancelAnimationFrame = function(id) { clearTimeout(id); };
    }
    if (typeof win.devicePixelRatio === 'undefined') {
        win.devicePixelRatio = wx.getSystemInfoSync().pixelRatio;
    }
    if (typeof win.innerWidth === 'undefined') {
        win.innerWidth = wx.getSystemInfoSync().screenWidth;
    }
    if (typeof win.innerHeight === 'undefined') {
        win.innerHeight = wx.getSystemInfoSync().screenHeight;
    }
    if (typeof win.addEventListener === 'undefined') {
        win.addEventListener = function() {};
    }
    if (typeof win.removeEventListener === 'undefined') {
        win.removeEventListener = function() {};
    }
    if (typeof win.location === 'undefined') {
        win.location = { href: './' };
    }
    if (!('Gdx' in win)) {
        win.Gdx = undefined;
    }
})();
console.log('[adapter] window polyfill done');

// === document polyfill ===
if (typeof document === 'undefined') {
    globalThis.document = {
        createElement: function(tag) {
            if (tag === 'canvas') return wx.createCanvas();
            return { style: {}, appendChild: function(){}, removeChild: function(){} };
        },
        getElementById: function() { return null; },
        addEventListener: function() {},
        removeEventListener: function() {},
        body: { appendChild: function(){}, removeChild: function(){} },
        head: { appendChild: function(){} },
        documentElement: { style: {} },
        querySelector: function() { return null; },
        querySelectorAll: function() { return []; }
    };
    console.log('[adapter] document polyfill created');
}

// === performance polyfill ===
if (typeof performance === 'undefined') {
    globalThis.performance = { now: Date.now };
    console.log('[adapter] performance polyfill created');
}

// === WebAssembly patch ===
if (typeof WXWebAssembly !== 'undefined') {
    if (typeof WebAssembly === 'undefined') {
        globalThis.WebAssembly = {};
    }
    var originalInstantiate = WebAssembly.instantiate;
    console.log('[adapter] WXWebAssembly detected, patching WebAssembly.instantiate');
    WebAssembly.instantiate = function(source, imports) {
        console.log('[adapter] WebAssembly.instantiate called, source type:', typeof source);
        if (source instanceof ArrayBuffer || source instanceof Uint8Array) {
            console.log('[adapter] Redirecting to WXWebAssembly.instantiate("subpackages/engine/gdx.wasm")');
            return WXWebAssembly.instantiate('subpackages/engine/gdx.wasm', imports);
        }
        console.log('[adapter] Falling through to originalInstantiate');
        return originalInstantiate ? originalInstantiate(source, imports) : Promise.reject(new Error('No WASM support'));
    };
}

// === atob polyfill ===
if (typeof atob === 'undefined') {
    var atob = function(base64) {
        var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
        var lookup = {};
        for (var i = 0; i < chars.length; i++) lookup[chars[i]] = i;
        var output = '';
        var buffer = 0, bufferLen = 0;
        for (var j = 0; j < base64.length; j++) {
            var ch = base64.charAt(j);
            if (ch === '=') break;
            buffer = (buffer << 6) | lookup[ch];
            bufferLen += 6;
            if (bufferLen >= 8) {
                bufferLen -= 8;
                output += String.fromCharCode((buffer >> bufferLen) & 0xFF);
            }
        }
        return output;
    };
    globalThis.atob = atob;
}

console.log('[adapter] Defining exports.setup');

exports.setup = function(canvas) {
    globalThis.canvas = canvas;
};

// === XMLHttpRequest polyfill (wraps wx.request) ===
if (typeof XMLHttpRequest === 'undefined') {
    var XHR = function() {
        this.readyState = 0;
        this.status = 0;
        this.statusText = '';
        this.responseText = '';
        this.response = '';
        this.responseType = '';
        this.responseHeaders = {};
        this._method = '';
        this._url = '';
        this._headers = {};
        this._async = true;
        this.onreadystatechange = null;
        this.onerror = null;
        this.onload = null;
    };
    XHR.UNSENT = 0;
    XHR.OPENED = 1;
    XHR.HEADERS_RECEIVED = 2;
    XHR.LOADING = 3;
    XHR.DONE = 4;
    XHR.prototype.open = function(method, url, async) {
        this._method = method;
        this._url = url;
        this._async = (async !== false);
        this.readyState = XHR.OPENED;
    };
    XHR.prototype.setRequestHeader = function(name, value) {
        this._headers[name] = value;
    };
    XHR.prototype.send = function(data) {
        var self = this;
        var opts = {
            url: self._url,
            method: self._method,
            header: self._headers,
            data: (data !== undefined && data !== null) ? data : undefined,
            dataType: 'text',
            success: function(res) {
                self.status = res.statusCode;
                self.statusText = '';
                self.responseText = (typeof res.data === 'string') ? res.data : JSON.stringify(res.data);
                self.response = self.responseText;
                self.responseHeaders = res.header || {};
                self.readyState = XHR.HEADERS_RECEIVED;
                if (self.onreadystatechange) self.onreadystatechange();
                self.readyState = XHR.LOADING;
                if (self.onreadystatechange) self.onreadystatechange();
                self.readyState = XHR.DONE;
                if (self.onreadystatechange) self.onreadystatechange();
                if (self.onload) self.onload();
            },
            fail: function(err) {
                self.status = 0;
                self.readyState = XHR.DONE;
                if (self.onreadystatechange) self.onreadystatechange();
                if (self.onerror) self.onerror(err);
            }
        };
        wx.request(opts);
    };
    XHR.prototype.abort = function() {};
    XHR.prototype.getAllResponseHeaders = function() {
        var result = '';
        for (var k in this.responseHeaders) {
            if (this.responseHeaders.hasOwnProperty(k)) {
                result += k + ': ' + this.responseHeaders[k] + '\r\n';
            }
        }
        return result;
    };
    XHR.prototype.getResponseHeader = function(name) {
        return this.responseHeaders[name] || null;
    };
    XHR.prototype.overrideMimeType = function() {};
    globalThis.XMLHttpRequest = XHR;
}
console.log('[adapter] Adapter fully loaded');
