// adapter.js — Browser polyfills for WeChat Mini Game
// Generated by MiniGameBackend

console.log('[adapter] Starting adapter initialization');
// === console polyfill (must be first — other polyfills use console.log) ===
if (typeof globalThis.console === 'undefined') {
    globalThis.console = { log: function(){}, error: function(){}, warn: function(){} };
}

// === window polyfill ===
// WeChat provides globalThis.window as a read-only getter on some platforms,
// but on real devices window may be completely undefined.
(function() {
    var win = (typeof window !== 'undefined') ? window : globalThis.window;
    if (!win) {
        win = globalThis;
        globalThis.window = globalThis;
        console.log('[adapter] window was undefined, created as globalThis alias');
    } else {
        console.log('[adapter] win exists, typeof win:', typeof win);
    }
    if (typeof win.requestAnimationFrame === 'undefined') {
        win.requestAnimationFrame = function(cb) { return setTimeout(cb, 16); };
    }
    if (typeof win.cancelAnimationFrame === 'undefined') {
        win.cancelAnimationFrame = function(id) { clearTimeout(id); };
    }
    if (typeof win.devicePixelRatio === 'undefined') {
        win.devicePixelRatio = wx.getSystemInfoSync().pixelRatio;
    }
    if (typeof win.innerWidth === 'undefined') {
        win.innerWidth = wx.getSystemInfoSync().screenWidth;
    }
    if (typeof win.innerHeight === 'undefined') {
        win.innerHeight = wx.getSystemInfoSync().screenHeight;
    }
    if (typeof win.addEventListener === 'undefined') {
        win.addEventListener = function() {};
    }
    if (typeof win.removeEventListener === 'undefined') {
        win.removeEventListener = function() {};
    }
    if (typeof win.location === 'undefined') {
        win.location = { href: './' };
    }
    if (!('Gdx' in win)) {
        win.Gdx = undefined;
    }
})();
console.log('[adapter] window polyfill done');

// === document polyfill ===
if (typeof document === 'undefined') {
    globalThis.document = {
        createElement: function(tag) {
            if (tag === 'canvas') return wx.createCanvas();
            return { style: {}, appendChild: function(){}, removeChild: function(){} };
        },
        getElementById: function() { return null; },
        addEventListener: function() {},
        removeEventListener: function() {},
        body: { appendChild: function(){}, removeChild: function(){} },
        head: { appendChild: function(){} },
        documentElement: { style: {} },
        querySelector: function() { return null; },
        querySelectorAll: function() { return []; }
    };
    console.log('[adapter] document polyfill created');
}

// === performance polyfill ===
if (typeof performance === 'undefined') {
    globalThis.performance = { now: Date.now };
    console.log('[adapter] performance polyfill created');
}

// === WebAssembly patch ===
if (typeof WXWebAssembly !== 'undefined') {
    if (typeof WebAssembly === 'undefined') {
        globalThis.WebAssembly = {};
    }
    var originalInstantiate = WebAssembly.instantiate;
    console.log('[adapter] WXWebAssembly detected, patching WebAssembly.instantiate');
    WebAssembly.instantiate = function(source, imports) {
        console.log('[adapter] WebAssembly.instantiate called, source type:', typeof source);
        if (source instanceof ArrayBuffer || source instanceof Uint8Array) {
            console.log('[adapter] Redirecting to WXWebAssembly.instantiate("subpackages/engine/gdx.wasm")');
            return WXWebAssembly.instantiate('subpackages/engine/gdx.wasm', imports);
        }
        console.log('[adapter] Falling through to originalInstantiate');
        return originalInstantiate ? originalInstantiate(source, imports) : Promise.reject(new Error('No WASM support'));
    };
}

// === atob polyfill ===
if (typeof atob === 'undefined') {
    var atob = function(base64) {
        var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
        var lookup = {};
        for (var i = 0; i < chars.length; i++) lookup[chars[i]] = i;
        var output = '';
        var buffer = 0, bufferLen = 0;
        for (var j = 0; j < base64.length; j++) {
            var ch = base64.charAt(j);
            if (ch === '=') break;
            buffer = (buffer << 6) | lookup[ch];
            bufferLen += 6;
            if (bufferLen >= 8) {
                bufferLen -= 8;
                output += String.fromCharCode((buffer >> bufferLen) & 0xFF);
            }
        }
        return output;
    };
    globalThis.atob = atob;
}

console.log('[adapter] Defining preloadAssets and exports.setup');
// === Asset preloader ===
var __preloadedAssets = {};
globalThis.__preloadedAssets = __preloadedAssets;

exports.preloadAssets = async function(onProgress) {
    var __preloadStart = Date.now();
    var __fileCount = 0;
    var __totalBytes = 0;
    console.log('[PERF] phase=preload_fs_read start=' + __preloadStart);
    try {
        var fs = wx.getFileSystemManager();
        var renameMap = {};
        try {
            var mapData = await new Promise(function(resolve, reject) {
                fs.readFile({
                    filePath: 'assets/rename-map.json',
                    encoding: 'utf-8',
                    success: function(res) { resolve(res.data); },
                    fail: function(err) { reject(err); }
                });
            });
            renameMap = JSON.parse(mapData);
            console.log('[adapter] Loaded rename map, entries:', Object.keys(renameMap).length);
        } catch(e) {
            console.log('[adapter] No rename-map.json found, proceeding without renaming');
        }
        var manifest = '';
        try {
            manifest = await new Promise(function(resolve, reject) {
                fs.readFile({
                    filePath: 'assets/preload.txt',
                    encoding: 'utf-8',
                    success: function(res) { resolve(res.data); },
                    fail: function(err) { reject(err); }
                });
            });
        } catch(e) {
            console.log('[adapter] preloadAssets: No manifest file, skipping');
            return;
        }
        var files = [];
        var lines = manifest.split('\n');
        for (var i = 0; i < lines.length; i++) {
            var line = lines[i].trim();
            if (!line) continue;
            var tokens = line.split(':');
            if (tokens.length < 4) continue;
            var assetType = tokens[1];
            var assetPath = tokens[2];
            if (!assetPath) continue;
            if (assetType === 'd') {
                __preloadedAssets[assetPath] = { type: 'dir', data: null };
            } else {
                files.push(assetPath);
            }
        }
        console.log('[PERF] phase=preload_manifest_parsed file_count=' + files.length + ' dur=' + (Date.now() - __preloadStart));
        var BATCH = 10;
        for (var i = 0; i < files.length; i += BATCH) {
            var batch = files.slice(i, Math.min(i + BATCH, files.length));
            var promises = batch.map(function(assetPath) {
                return new Promise(function(resolve) {
                    var readPath = renameMap[assetPath] || assetPath;
                    fs.readFile({
                        filePath: 'assets' + readPath,
                        success: function(res) {
                            __preloadedAssets[assetPath] = { type: 'file', data: res.data };
                            __fileCount++;
                            if (res.data && res.data.byteLength) __totalBytes += res.data.byteLength;
                            resolve();
                        },
                        fail: function(err) {
                            console.error('[adapter] Failed:', assetPath, err.errMsg);
                            __preloadedAssets[assetPath] = { type: 'file', data: new ArrayBuffer(0) };
                            resolve();
                        }
                    });
                });
            });
            await Promise.all(promises);
            if (onProgress) onProgress(Math.min(i + BATCH, files.length), files.length);
            if ((i + BATCH) % 50 === 0 || i + BATCH >= files.length) {
                console.log('[PERF] phase=preload_batch files_so_far=' + Math.min(i + BATCH, files.length) + '/' + files.length + ' dur=' + (Date.now() - __preloadStart));
            }
            await new Promise(function(r) { globalThis.requestAnimationFrame(r); });
        }
        var __preloadEnd = Date.now();
        console.log('[PERF] phase=preload_fs_read end=' + __preloadEnd + ' dur=' + (__preloadEnd - __preloadStart) + ' files=' + __fileCount + ' bytes=' + __totalBytes);
        console.log('[adapter] preloadAssets complete, assets:', Object.keys(__preloadedAssets).length);
    } catch(e) {
        console.error('[adapter] preloadAssets error:', e);
    }
};

exports.setup = function(canvas) {
    globalThis.canvas = canvas;
};

// === XMLHttpRequest polyfill (wraps wx.request) ===
if (typeof XMLHttpRequest === 'undefined') {
    var XHR = function() {
        this.readyState = 0;
        this.status = 0;
        this.statusText = '';
        this.responseText = '';
        this.response = '';
        this.responseType = '';
        this.responseHeaders = {};
        this._method = '';
        this._url = '';
        this._headers = {};
        this._async = true;
        this.onreadystatechange = null;
        this.onerror = null;
        this.onload = null;
    };
    XHR.UNSENT = 0;
    XHR.OPENED = 1;
    XHR.HEADERS_RECEIVED = 2;
    XHR.LOADING = 3;
    XHR.DONE = 4;
    XHR.prototype.open = function(method, url, async) {
        this._method = method;
        this._url = url;
        this._async = (async !== false);
        this.readyState = XHR.OPENED;
    };
    XHR.prototype.setRequestHeader = function(name, value) {
        this._headers[name] = value;
    };
    XHR.prototype.send = function(data) {
        var self = this;
        var opts = {
            url: self._url,
            method: self._method,
            header: self._headers,
            data: (data !== undefined && data !== null) ? data : undefined,
            dataType: 'text',
            success: function(res) {
                self.status = res.statusCode;
                self.statusText = '';
                self.responseText = (typeof res.data === 'string') ? res.data : JSON.stringify(res.data);
                self.response = self.responseText;
                self.responseHeaders = res.header || {};
                self.readyState = XHR.HEADERS_RECEIVED;
                if (self.onreadystatechange) self.onreadystatechange();
                self.readyState = XHR.LOADING;
                if (self.onreadystatechange) self.onreadystatechange();
                self.readyState = XHR.DONE;
                if (self.onreadystatechange) self.onreadystatechange();
                if (self.onload) self.onload();
            },
            fail: function(err) {
                self.status = 0;
                self.readyState = XHR.DONE;
                if (self.onreadystatechange) self.onreadystatechange();
                if (self.onerror) self.onerror(err);
            }
        };
        wx.request(opts);
    };
    XHR.prototype.abort = function() {};
    XHR.prototype.getAllResponseHeaders = function() {
        var result = '';
        for (var k in this.responseHeaders) {
            if (this.responseHeaders.hasOwnProperty(k)) {
                result += k + ': ' + this.responseHeaders[k] + '\r\n';
            }
        }
        return result;
    };
    XHR.prototype.getResponseHeader = function(name) {
        return this.responseHeaders[name] || null;
    };
    XHR.prototype.overrideMimeType = function() {};
    globalThis.XMLHttpRequest = XHR;
}
console.log('[adapter] Adapter fully loaded');
