// game.js — WeChat Mini Game entry point
// Generated by MiniGameBackend

// === Performance timing helpers ===
var __perf = { t0: Date.now(), marks: {} };
__perf.marks['game_js_entry'] = __perf.t0;
function __perfMark(name) { __perf.marks[name] = Date.now(); }
function __perfReport(phase, startMark) {
    var start = __perf.marks[startMark];
    if (start === undefined) { console.log('[PERF] phase=' + phase + ' MISSING_START=' + startMark); return; }
    var end = Date.now();
    console.log('[PERF] phase=' + phase + ' start=' + start + ' end=' + end + ' dur=' + (end - start));
}
console.log('[PERF] phase=game_js_entry start=' + __perf.t0);

console.log('[game.js] Requiring adapter...');
var adapter = require('./adapter.js');
__perfMark('adapter_loaded');
var firstScreen = require('./first-screen');
__perfMark('first_screen_loaded');
console.log('[game.js] Adapter and first-screen loaded');

// Create single canvas for WebGL
var canvas = wx.createCanvas();
adapter.setup(canvas);
firstScreen.start(canvas);
__perfMark('canvas_ready');
console.log('[game.js] Canvas created and splash drawn', canvas.width, 'x', canvas.height);

// Helper: load subpackage with error handling
function loadSubpackage(name) {
    if (typeof wx.loadSubpackage !== 'function') {
        console.log('[game.js] wx.loadSubpackage not available, skipping ' + name);
        return Promise.resolve();
    }
    return new Promise(function(resolve) {
        wx.loadSubpackage({
            name: name,
            success: function() {
                console.log('[game.js] Subpackage "' + name + '" loaded');
                resolve();
            },
            fail: function(err) {
                console.log('[game.js] Subpackage "' + name + '" load issue:', err.errMsg || err);
                resolve();
            }
        });
    });
}

async function startGame() {
    try {
        // Phase 1: Load all subpackages in parallel
        console.log('[game.js] Loading all subpackages in parallel...');
        __perfMark('subpackages_start');
        await Promise.all([
            loadSubpackage('engine'),
            loadSubpackage('assets'),
            loadSubpackage('game')
        ]);
        __perfMark('subpackages_done');
        __perfReport('phase1_subpackages', 'subpackages_start');
        console.log('[game.js] All subpackages loaded');

        // Phase 3: Wait for engine to initialize (Gdx bridge set by gdx.wasm.js)
        console.log('[game.js] Waiting for engine initialization...');
        __perfMark('engine_wait_start');
        var gdxWaitStart = Date.now();
        while (typeof window.Gdx === 'undefined') {
            if (Date.now() - gdxWaitStart > 30000) {
                throw new Error('Timed out waiting for Gdx to initialize (30s)');
            }
            await new Promise(function(r) { setTimeout(r, 50); });
        }
        __perfMark('engine_ready');
        __perfReport('phase3_engine_wait', 'engine_wait_start');
        console.log('[game.js] window.Gdx available, type:', typeof window.Gdx);

        // Phase 5: Start the compiled game via globalThis bridge
        var mainModule = globalThis.__gameApp;
        if (mainModule && mainModule.main) {
            console.log('[game.js] Calling main()...');
            __perfMark('main_call');
            mainModule.main([${mainClassArgs}]);
            __perfMark('main_returned');
            __perfReport('phase5_main', 'main_call');
            console.log('[game.js] main() returned');
        } else {
            console.error('[game.js] ERROR: __gameApp not available, cannot call main()');
        }

        // Redraw splash to bridge canvas resize gap
        firstScreen.redraw();
        __perfMark('first_frame_complete');
        __perfReport('total_startup', 'game_js_entry');
        // Summary
        (function() {
            var m = __perf.marks;
            var safe = function(a, b) { return (m[a] !== undefined && m[b] !== undefined) ? (m[a] - m[b]) : 'N/A'; };
            console.log('[PERF] summary total_ms=' + safe('first_frame_complete', 'game_js_entry') +
                ' subpackages_ms=' + safe('subpackages_done', 'subpackages_start') +
                ' engine_wait_ms=' + safe('engine_ready', 'engine_wait_start') +
                ' main_ms=' + safe('main_returned', 'main_call'));
        })();
    } catch (err) {
        console.error('[game.js] FAILED:', err);
    }
}

startGame();
