// game.js — WeChat Mini Game entry point
// Generated by MiniGameBackend

// === Performance timing helpers ===
var __perf = { t0: Date.now(), marks: {} };
__perf.marks['game_js_entry'] = __perf.t0;
function __perfMark(name) { __perf.marks[name] = Date.now(); }
function __perfReport(phase, startMark) {
    var start = __perf.marks[startMark];
    if (start === undefined) { console.log('[PERF] phase=' + phase + ' MISSING_START=' + startMark); return; }
    var end = Date.now();
    console.log('[PERF] phase=' + phase + ' start=' + start + ' end=' + end + ' dur=' + (end - start));
}
console.log('[PERF] phase=game_js_entry start=' + __perf.t0);

console.log('[game.js] Requiring adapter...');
var adapter = require('./adapter.js');
__perfMark('adapter_loaded');
var firstScreen = require('./first-screen');
__perfMark('first_screen_loaded');
console.log('[game.js] Adapter and first-screen loaded');

// Create single canvas for WebGL
var canvas = wx.createCanvas();
adapter.setup(canvas);
firstScreen.start(canvas);
__perfMark('canvas_ready');
console.log('[game.js] Canvas created and splash drawn', canvas.width, 'x', canvas.height);

// Helper: load subpackage with error handling
function loadSubpackage(name) {
    if (typeof wx.loadSubpackage !== 'function') {
        console.log('[game.js] wx.loadSubpackage not available, skipping ' + name);
        return Promise.resolve();
    }
    return new Promise(function(resolve) {
        wx.loadSubpackage({
            name: name,
            success: function() {
                console.log('[game.js] Subpackage "' + name + '" loaded');
                resolve();
            },
            fail: function(err) {
                console.log('[game.js] Subpackage "' + name + '" load issue:', err.errMsg || err);
                resolve();
            }
        });
    });
}

async function startGame() {
    try {
        // Phase 1: Load engine and assets in parallel
        console.log('[game.js] Loading engine and assets in parallel...');
        __perfMark('subpackages_start');
        await Promise.all([
            loadSubpackage('engine'),
            loadSubpackage('assets')
        ]);
        __perfMark('subpackages_done');
        __perfReport('phase1_subpackages', 'subpackages_start');
        console.log('[game.js] Engine and assets subpackages loaded');

        // Phase 2+3+4: Overlap game subpackage load with preload and engine wait.
        // We kick off loadSubpackage('game') immediately (non-blocking), then run preload
        // and engine wait sequentially. The game subpackage loads in the background via
        // wx.loadSubpackage's own callback — no Promise.all needed.
        // Safe because: require('./app.js') is pure class registration (no $clinit, no
        // asset/WASM access during module eval), __preloadedAssets is only read inside main().

        // Step 1: Fire off game subpackage load immediately (runs in background)
        console.log('[game.js] Kicking off game subpackage load in background...');
        __perfMark('game_code_start');
        var gameLoadPromise = loadSubpackage('game');

        // Step 2: Preload assets (game subpackage loads concurrently via wx callback)
        console.log('[game.js] Preloading assets (game subpackage loading in background)...');
        __perfMark('preload_start');
        await adapter.preloadAssets(function(loaded, total) {
            firstScreen.setProgress(loaded / total);
        });
        __perfMark('preload_done');
        __perfReport('phase2_preload_assets', 'preload_start');
        console.log('[game.js] Assets preloaded, count:', globalThis.__preloadedAssets ? Object.keys(globalThis.__preloadedAssets).length : 0);

        // Step 3: Wait for engine to initialize (Gdx bridge set by gdx.wasm.js)
        console.log('[game.js] Waiting for engine initialization...');
        __perfMark('engine_wait_start');
        var gdxWaitStart = Date.now();
        while (typeof window.Gdx === 'undefined') {
            if (Date.now() - gdxWaitStart > 30000) {
                throw new Error('Timed out waiting for Gdx to initialize (30s)');
            }
            await new Promise(function(r) { setTimeout(r, 50); });
        }
        __perfMark('engine_ready');
        __perfReport('phase3_engine_wait', 'engine_wait_start');
        console.log('[game.js] window.Gdx available, type:', typeof window.Gdx);

        // Step 4: Await game subpackage (may already be done — loads overlapped with steps 2+3)
        __perfMark('await_game_start');
        await gameLoadPromise;
        __perfMark('game_code_done');
        __perfReport('phase4_game_code', 'game_code_start');
        __perfReport('phase4_await_game', 'await_game_start');
        console.log('[game.js] Game code subpackage loaded (overlapped:', (__perf.marks['await_game_start'] !== undefined && __perf.marks['game_code_done'] !== undefined) ? (__perf.marks['game_code_done'] - __perf.marks['await_game_start']) + 'ms await' : 'N/A', ')');

        // Phase 5: Start the compiled game via globalThis bridge
        var mainModule = globalThis.__gameApp;
        if (mainModule && mainModule.main) {
            console.log('[game.js] Calling main()...');
            __perfMark('main_call');
            mainModule.main([${mainClassArgs}]);
            __perfMark('main_returned');
            __perfReport('phase5_main', 'main_call');
            console.log('[game.js] main() returned');
        } else {
            console.error('[game.js] ERROR: __gameApp not available, cannot call main()');
        }

        // Redraw splash to bridge canvas resize gap
        firstScreen.redraw();
        __perfMark('first_frame_complete');
        __perfReport('total_startup', 'game_js_entry');
        // Summary
        (function() {
            var m = __perf.marks;
            var safe = function(a, b) { return (m[a] !== undefined && m[b] !== undefined) ? (m[a] - m[b]) : 'N/A'; };
            console.log('[PERF] summary total_ms=' + safe('first_frame_complete', 'game_js_entry') +
                ' subpackages_ms=' + safe('subpackages_done', 'subpackages_start') +
                ' preload_ms=' + safe('preload_done', 'preload_start') +
                ' engine_wait_ms=' + safe('engine_ready', 'engine_wait_start') +
                ' game_code_ms=' + safe('game_code_done', 'game_code_start') +
                ' main_ms=' + safe('main_returned', 'main_call'));
        })();
    } catch (err) {
        console.error('[game.js] FAILED:', err);
    }
}

startGame();
