// game.js — WeChat Mini Game entry point
// Generated by MiniGameBackend

// === Performance timing helpers ===
var __perf = { t0: Date.now(), marks: {} };
__perf.marks['game_js_entry'] = __perf.t0;
function __perfMark(name) { __perf.marks[name] = Date.now(); }
function __perfReport(phase, startMark) {
    var start = __perf.marks[startMark];
    if (start === undefined) { console.log('[PERF] phase=' + phase + ' MISSING_START=' + startMark); return; }
    var end = Date.now();
    console.log('[PERF] phase=' + phase + ' start=' + start + ' end=' + end + ' dur=' + (end - start));
}
console.log('[PERF] phase=game_js_entry start=' + __perf.t0);

console.log('[game.js] Requiring adapter...');
var adapter = require('./adapter.js');
__perfMark('adapter_loaded');
var firstScreen = require('./first-screen');
__perfMark('first_screen_loaded');
console.log('[game.js] Adapter and first-screen loaded');

// Create single canvas for WebGL
var canvas = wx.createCanvas();
adapter.setup(canvas);
firstScreen.start(canvas);
__perfMark('canvas_ready');
console.log('[game.js] Canvas created and splash drawn', canvas.width, 'x', canvas.height);

// Helper: load subpackage with error handling
function loadSubpackage(name) {
    if (typeof wx.loadSubpackage !== 'function') {
        console.log('[game.js] wx.loadSubpackage not available, skipping ' + name);
        return Promise.resolve();
    }
    return new Promise(function(resolve) {
        wx.loadSubpackage({
            name: name,
            success: function() {
                console.log('[game.js] Subpackage "' + name + '" loaded');
                resolve();
            },
            fail: function(err) {
                console.log('[game.js] Subpackage "' + name + '" load issue:', err.errMsg || err);
                resolve();
            }
        });
    });
}

async function startGame() {
    try {
        // Phase 0: Install setter on window.Gdx so we get notified
        // instantly when gdx.wasm.js sets it (via asyncCall).
        // Must happen BEFORE loadSubpackage('engine') triggers require('./gdx.wasm.js').
        var gdxReadyPromise = new Promise(function(resolve) {
            if (typeof window.Gdx !== 'undefined') {
                resolve();
                return;
            }
            Object.defineProperty(window, 'Gdx', {
                configurable: true,
                set: function(val) {
                    Object.defineProperty(window, 'Gdx', {
                        configurable: true, writable: true, enumerable: true, value: val
                    });
                    resolve();
                }
            });
        });

        // Phase 1: Start all subpackage loads in parallel
        __perfMark('subpackages_start');
        var enginePromise = loadSubpackage('engine');
        var assetsPromise = loadSubpackage('assets');
        var gamePromise = loadSubpackage('game');

        // Track engine subpackage resolution separately
        var engineReadyPromise = enginePromise.then(function() {
            __perfMark('engine_loaded');
            __perfReport('phase1_engine', 'subpackages_start');
        });

        // Phase 2: Gdx fires via setter — no polling needed
        var gdxPromise = gdxReadyPromise.then(function() {
            __perfMark('gdx_ready');
            __perfReport('phase3_engine_wait', 'engine_loaded');
        });

        // Phase 2.5: Pre-cache manifest files when assets resolve
        // Reads preload.txt and rename-map.json during the I/O wait phase
        // so Java's InternalStorage finds them in cache instead of reading from disk
        var assetsReadyPromise = assetsPromise.then(function() {
            __perfMark('assets_loaded');
            __perfReport('phase1_assets', 'subpackages_start');
            try {
                var fsm = wx.getFileSystemManager();
                globalThis.__preloadedTextFiles = {};
                try { globalThis.__preloadedTextFiles['assets/preload.txt'] = fsm.readFileSync('assets/preload.txt', 'utf-8'); } catch(e) {}
                try { globalThis.__preloadedTextFiles['assets/rename-map.json'] = fsm.readFileSync('assets/rename-map.json', 'utf-8'); } catch(e) {}
            } catch(e) {}
        });

        // Track when game subpackage resolves
        var gameReadyPromise = gamePromise.then(function() {
            __perfMark('game_loaded');
            __perfReport('phase1_game', 'subpackages_start');
        });

        // Wait for Gdx ready + game loaded + assets ready (with pre-cached manifests)
        // gdxPromise resolves only after engine subpackage loads (window.Gdx set by gdx.wasm.js),
        // which means freetype-loader.js has already set globalThis.__freetypeReady by this point.
        await Promise.all([gdxPromise, gameReadyPromise, assetsReadyPromise]);
        // Now await freetype WASM — guaranteed to be set since engine subpackage is loaded
        if (globalThis.__freetypeReady) await globalThis.__freetypeReady;
        __perfMark('all_ready');
        __perfReport('phase1_pipeline', 'subpackages_start');

        // Phase 5: Start the compiled game via globalThis bridge
        var mainModule = globalThis.__gameApp;
        if (mainModule && mainModule.main) {
            __perfMark('main_call');
            mainModule.main([${mainClassArgs}]);
            __perfMark('main_returned');
            __perfReport('phase5_main', 'main_call');
        } else {
            console.error('[game.js] ERROR: __gameApp not available, cannot call main()');
        }

        // Redraw splash to bridge canvas resize gap
        firstScreen.redraw();
        __perfMark('first_frame_complete');
        __perfReport('total_startup', 'game_js_entry');
        // Summary
        (function() {
            var m = __perf.marks;
            var safe = function(a, b) { return (m[a] !== undefined && m[b] !== undefined) ? (m[a] - m[b]) : 'N/A'; };
            console.log('[PERF] summary total_ms=' + safe('first_frame_complete', 'game_js_entry') +
                ' pipeline_ms=' + safe('all_ready', 'subpackages_start') +
                ' engine_ms=' + safe('engine_loaded', 'subpackages_start') +
                ' gdx_wait_ms=' + safe('gdx_ready', 'engine_loaded') +
                ' game_ms=' + safe('game_loaded', 'subpackages_start') +
                ' assets_ms=' + safe('assets_loaded', 'subpackages_start') +
                ' main_ms=' + safe('main_returned', 'main_call'));
        })();
    } catch (err) {
        console.error('[game.js] FAILED:', err);
    }
}

startGame();
