package com.github.xpenatan.gdx.teavm.backends.minigame.config.backend;

import com.badlogic.gdx.files.FileHandle;
import com.github.xpenatan.gdx.teavm.backends.minigame.config.MiniGameBuildConfiguration;
import com.github.xpenatan.gdx.teavm.backends.shared.config.AssetFilter;
import com.github.xpenatan.gdx.teavm.backends.shared.config.AssetsCopy;
import com.github.xpenatan.gdx.teavm.backends.shared.config.compiler.TeaBackend;
import com.github.xpenatan.gdx.teavm.backends.shared.config.compiler.TeaCompilerData;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import org.teavm.tooling.TeaVMTargetType;

/**
 * Build backend for WeChat Mini Game.
 * Generates game.js, game.json, project.config.json, and adapter/index.js
 * instead of index.html + web.xml.
 */
public class MiniGameBackend extends TeaBackend {

    public String appId = "";
    public String orientation = "portrait";
    public String description = "WeChat Mini Game";
    public String targetFileName = "app";
    public String mainClassArgs = "";
    public AssetFilter scriptFilter;

    public MiniGameBackend setAppId(String appId) {
        this.appId = appId;
        return this;
    }

    public MiniGameBackend setOrientation(String orientation) {
        this.orientation = orientation;
        return this;
    }

    public MiniGameBackend setDescription(String description) {
        this.description = description;
        return this;
    }

    public MiniGameBackend setTargetFileName(String targetFileName) {
        this.targetFileName = targetFileName;
        return this;
    }

    public MiniGameBackend setMainClassArgs(String mainClassArgs) {
        this.mainClassArgs = mainClassArgs;
        return this;
    }

    public MiniGameBackend setScriptFilter(AssetFilter scriptFilter) {
        this.scriptFilter = scriptFilter;
        return this;
    }

    @Override
    protected void setup(TeaCompilerData data) {
        targetType = TeaVMTargetType.JAVASCRIPT;
        tool.setTargetFileName(data.outputName + ".js");

        if(data.releasePath != null) {
            releasePath = new FileHandle(data.releasePath.getAbsolutePath().replace("\\", "/"));
        } else {
            releasePath = new FileHandle(new File(data.output, "minigame").getAbsolutePath().replace("\\", "/"));
        }
        tool.setTargetDirectory(releasePath.file());
        setupMinigame(data);
    }

    @Override
    protected void build(TeaCompilerData data) {
        super.build(data);
        // Post-build steps
        fixFreetypeModuleScoping();
    }

    private void setupMinigame(TeaCompilerData data) {
        if (appId == null || appId.isEmpty()) {
            System.out.println("[MiniGameBackend] WARNING: appId is empty. Set via setAppId() for production builds.");
        }
        generateGameJson();
        generateProjectConfigJson();
        generateGameJs(data);
        generateAdapter();
    }

    /**
     * Generate game.json — WeChat Mini Game configuration.
     */
    private void generateGameJson() {
        String json = "{\n" +
            "    \"deviceOrientation\": \"" + orientation + "\",\n" +
            "    \"networkTimeout\": {\n" +
            "        \"request\": 5000,\n" +
            "        \"connectSocket\": 5000,\n" +
            "        \"uploadFile\": 5000,\n" +
            "        \"downloadFile\": 500000\n" +
            "    },\n" +
            "    \"subpackages\": [\n" +
            "        { \"name\": \"engine\", \"root\": \"scripts/\" },\n" +
            "        { \"name\": \"assets\", \"root\": \"assets/\" }\n" +
            "    ]\n" +
            "}\n";

        FileHandle gameJson = releasePath.child("game.json");
        gameJson.writeString(json, false);
    }

    /**
     * Generate project.config.json — WeChat DevTools project config.
     */
    private void generateProjectConfigJson() {
        String json = "{\n" +
            "    \"description\": \"" + description + "\",\n" +
            "    \"setting\": {\n" +
            "        \"urlCheck\": false,\n" +
            "        \"es6\": true\n" +
            "    },\n" +
            "    \"compileType\": \"game\",\n" +
            "    \"appid\": \"" + appId + "\",\n" +
            "    \"libVersion\": \"3.12.1\"\n" +
            "}\n";

        FileHandle projectConfig = releasePath.child("project.config.json");
        projectConfig.writeString(json, false);
    }

    /**
     * Generate game.js — Main package entry point.
     */
    private void generateGameJs(TeaCompilerData data) {
        String js = "// game.js — WeChat Mini Game entry point\n" +
            "// Generated by MiniGameBackend\n\n" +
            "const { setup } = require('./adapter/index.js');\n\n" +
            "// Phase 1: Setup shims and canvas (synchronous)\n" +
            "const canvas = wx.createCanvas();\n" +
            "setup(canvas);\n\n" +
            "// Phase 2: Draw loading screen\n" +
            "const ctx = canvas.getContext('2d');\n" +
            "ctx.fillStyle = '#1a472a';\n" +
            "ctx.fillRect(0, 0, canvas.width, canvas.height);\n" +
            "ctx.fillStyle = 'white';\n" +
            "ctx.font = '20px sans-serif';\n" +
            "ctx.textAlign = 'center';\n" +
            "ctx.fillText('Loading...', canvas.width / 2, canvas.height / 2);\n\n" +
            "// Phase 3: Load subpackages and start game\n" +
            "async function startGame() {\n" +
            "    try {\n" +
            "        // Load engine subpackage (freetype.js, gdx.wasm.js)\n" +
            "        if (typeof wx.loadSubpackage === 'function') {\n" +
            "            await wx.loadSubpackage({ name: 'engine' }).promise;\n" +
            "        }\n\n" +
            "        // Load freetype.js (sets globalThis.Module synchronously)\n" +
            "        try { require('./scripts/freetype.js'); } catch(e) { /* optional */ }\n\n" +
            "        // Load gdx.wasm.js (sets window.Gdx ASYNC via self-execution)\n" +
            "        try {\n" +
            "            require('./scripts/gdx.wasm.js');\n" +
            "            // Wait for Gdx to be available (with timeout)\n" +
            "            var gdxWaitStart = Date.now();\n" +
            "            while (typeof window.Gdx === 'undefined') {\n" +
            "                if (Date.now() - gdxWaitStart > 30000) {\n" +
            "                    throw new Error('Timed out waiting for Gdx to initialize (30s)');\n" +
            "                }\n" +
            "                await new Promise(r => setTimeout(r, 50));\n" +
            "            }\n" +
            "        } catch(e) { if (e.message && e.message.indexOf('Timed out') >= 0) throw e; }\n\n" +
            "        // Start the compiled game\n" +
            "        const mainModule = require('./" + data.outputName + ".js');\n" +
            "        if (mainModule && mainModule.main) {\n" +
            "            mainModule.main([" + mainClassArgs + "]);\n" +
            "        }\n" +
            "    } catch (err) {\n" +
            "        console.error('Failed to load:', err);\n" +
            "    }\n" +
            "}\n\n" +
            "startGame();\n";

        FileHandle gameJs = releasePath.child("game.js");
        gameJs.writeString(js, false);
    }

    /**
     * Generate adapter/index.js — Browser polyfills for WeChat environment.
     */
    private void generateAdapter() {
        FileHandle adapterDir = releasePath.child("adapter");
        adapterDir.mkdirs();

        String js = "// adapter/index.js — Minimal browser polyfills for WeChat Mini Game\n" +
            "// Generated by MiniGameBackend\n\n" +
            "// === window polyfill ===\n" +
            "if (typeof window === 'undefined') {\n" +
            "    var window = {\n" +
            "        requestAnimationFrame: typeof requestAnimationFrame !== 'undefined' ? requestAnimationFrame : function(cb) { return setTimeout(cb, 16); },\n" +
            "        cancelAnimationFrame: typeof cancelAnimationFrame !== 'undefined' ? cancelAnimationFrame : function(id) { clearTimeout(id); },\n" +
            "        devicePixelRatio: wx.getSystemInfoSync().pixelRatio,\n" +
            "        innerWidth: wx.getSystemInfoSync().screenWidth,\n" +
            "        innerHeight: wx.getSystemInfoSync().screenHeight,\n" +
            "        addEventListener: function() {},\n" +
            "        removeEventListener: function() {},\n" +
            "        location: { href: './' },\n" +
            "        Gdx: undefined\n" +
            "    };\n" +
            "    globalThis.window = window;\n" +
            "}\n\n" +
            "// === WebAssembly patch ===\n" +
            "if (typeof WXWebAssembly !== 'undefined') {\n" +
            "    if (typeof WebAssembly === 'undefined') {\n" +
            "        globalThis.WebAssembly = {};\n" +
            "    }\n" +
            "    var originalInstantiate = WebAssembly.instantiate;\n" +
            "    WebAssembly.instantiate = function(source, imports) {\n" +
            "        if (source instanceof ArrayBuffer || source instanceof Uint8Array) {\n" +
            "            return WXWebAssembly.instantiate('scripts/gdx.wasm', imports);\n" +
            "        }\n" +
            "        return originalInstantiate ? originalInstantiate(source, imports) : Promise.reject(new Error('No WASM support'));\n" +
            "    };\n" +
            "}\n\n" +
            "// === atob polyfill ===\n" +
            "if (typeof atob === 'undefined') {\n" +
            "    var atob = function(base64) {\n" +
            "        var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';\n" +
            "        var lookup = {};\n" +
            "        for (var i = 0; i < chars.length; i++) lookup[chars[i]] = i;\n" +
            "        var output = '';\n" +
            "        var buffer = 0, bufferLen = 0;\n" +
            "        for (var j = 0; j < base64.length; j++) {\n" +
            "            var ch = base64.charAt(j);\n" +
            "            if (ch === '=') break;\n" +
            "            buffer = (buffer << 6) | lookup[ch];\n" +
            "            bufferLen += 6;\n" +
            "            if (bufferLen >= 8) {\n" +
            "                bufferLen -= 8;\n" +
            "                output += String.fromCharCode((buffer >> bufferLen) & 0xFF);\n" +
            "            }\n" +
            "        }\n" +
            "        return output;\n" +
            "    };\n" +
            "    globalThis.atob = atob;\n" +
            "}\n\n" +
            "// === console polyfill (defensive) ===\n" +
            "if (typeof console === 'undefined') {\n" +
            "    var console = { log: function(){}, error: function(){}, warn: function(){} };\n" +
            "    globalThis.console = console;\n" +
            "}\n\n" +
            "exports.setup = function(canvas) {\n" +
            "    globalThis.canvas = canvas;\n" +
            "};\n\n" +
            "// === XMLHttpRequest polyfill (wraps wx.request) ===\n" +
            "if (typeof XMLHttpRequest === 'undefined') {\n" +
            "    var XHR = function() {\n" +
            "        this.readyState = 0;\n" +
            "        this.status = 0;\n" +
            "        this.statusText = '';\n" +
            "        this.responseText = '';\n" +
            "        this.response = '';\n" +
            "        this.responseType = '';\n" +
            "        this.responseHeaders = {};\n" +
            "        this._method = '';\n" +
            "        this._url = '';\n" +
            "        this._headers = {};\n" +
            "        this._async = true;\n" +
            "        this.onreadystatechange = null;\n" +
            "        this.onerror = null;\n" +
            "        this.onload = null;\n" +
            "    };\n" +
            "    XHR.UNSENT = 0;\n" +
            "    XHR.OPENED = 1;\n" +
            "    XHR.HEADERS_RECEIVED = 2;\n" +
            "    XHR.LOADING = 3;\n" +
            "    XHR.DONE = 4;\n" +
            "    XHR.prototype.open = function(method, url, async) {\n" +
            "        this._method = method;\n" +
            "        this._url = url;\n" +
            "        this._async = (async !== false);\n" +
            "        this.readyState = XHR.OPENED;\n" +
            "    };\n" +
            "    XHR.prototype.setRequestHeader = function(name, value) {\n" +
            "        this._headers[name] = value;\n" +
            "    };\n" +
            "    XHR.prototype.send = function(data) {\n" +
            "        var self = this;\n" +
            "        var opts = {\n" +
            "            url: self._url,\n" +
            "            method: self._method,\n" +
            "            header: self._headers,\n" +
            "            data: (data !== undefined && data !== null) ? data : undefined,\n" +
            "            dataType: 'text',\n" +
            "            success: function(res) {\n" +
            "                self.status = res.statusCode;\n" +
            "                self.statusText = '';\n" +
            "                self.responseText = (typeof res.data === 'string') ? res.data : JSON.stringify(res.data);\n" +
            "                self.response = self.responseText;\n" +
            "                self.responseHeaders = res.header || {};\n" +
            "                self.readyState = XHR.HEADERS_RECEIVED;\n" +
            "                if (self.onreadystatechange) self.onreadystatechange();\n" +
            "                self.readyState = XHR.LOADING;\n" +
            "                if (self.onreadystatechange) self.onreadystatechange();\n" +
            "                self.readyState = XHR.DONE;\n" +
            "                if (self.onreadystatechange) self.onreadystatechange();\n" +
            "                if (self.onload) self.onload();\n" +
            "            },\n" +
            "            fail: function(err) {\n" +
            "                self.status = 0;\n" +
            "                self.readyState = XHR.DONE;\n" +
            "                if (self.onreadystatechange) self.onreadystatechange();\n" +
            "                if (self.onerror) self.onerror(err);\n" +
            "            }\n" +
            "        };\n" +
            "        wx.request(opts);\n" +
            "    };\n" +
            "    XHR.prototype.abort = function() {};\n" +
            "    XHR.prototype.getAllResponseHeaders = function() {\n" +
            "        var result = '';\n" +
            "        for (var k in this.responseHeaders) {\n" +
            "            if (this.responseHeaders.hasOwnProperty(k)) {\n" +
            "                result += k + ': ' + this.responseHeaders[k] + '\\r\\n';\n" +
            "            }\n" +
            "        }\n" +
            "        return result;\n" +
            "    };\n" +
            "    XHR.prototype.getResponseHeader = function(name) {\n" +
            "        return this.responseHeaders[name] || null;\n" +
            "    };\n" +
            "    XHR.prototype.overrideMimeType = function() {};\n" +
            "    globalThis.XMLHttpRequest = XHR;\n" +
            "}\n";

        FileHandle adapterJs = adapterDir.child("index.js");
        adapterJs.writeString(js, false);
    }

    /**
     * Fix freetype.js Module scoping — inject globalThis.Module = Module
     * so that compiled code can access it.
     */
    private void fixFreetypeModuleScoping() {
        FileHandle scriptsFolder = releasePath.child("scripts");
        FileHandle freetypeJs = scriptsFolder.child("freetype.js");
        if (freetypeJs.exists()) {
            try {
                String content = freetypeJs.readString();
                content = content.replace(
                    "Module[\"noExitRuntime\"]=true;",
                    "Module[\"noExitRuntime\"]=true;if(typeof globalThis!==\"undefined\"){globalThis.Module=Module}"
                );
                freetypeJs.writeString(content, false);
            } catch (Exception e) {
                // Non-critical, continue
            }
        }
    }

    @Override
    protected void copyAssets(TeaCompilerData data) {
        super.copyAssets(data);

        // Copy scripts to scripts/ directory
        FileHandle scriptsFolder = releasePath.child("scripts");
        AssetsCopy.copyResources(classLoader, scripts, scriptFilter, scriptsFolder);
    }
}
